all:
  hosts:
  children:
    gateway:
      hosts:
        tokyo.prim.tedween.de:
          ansible_host: prim.tedween.de
          local_ip: 10.11.12.1
      vars:
        node_type: main
    clustermember:
      hosts:
        rio.prim.tedween.de:
          ansible_host: 10.11.12.11
          local_ip: 10.11.12.11
        helsinki.prim.tedween.de:
          ansible_host: 10.11.12.12
          local_ip: 10.11.12.12
        denver.prim.tedween.de:
          ansible_host: 10.11.12.13
          local_ip: 10.11.12.13
        stockholm.prim.tedween.de:
          ansible_host: 10.11.12.14
          local_ip: 10.11.12.14
      vars:
        node_type: worker
        ansible_ssh_common_args: -J root@prim.tedween.de
  vars:
    ansible_ssh_user: root
