- name: Setup Gateway
  hosts: gateway
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install nginx & certbot
      ansible.builtin.package:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Add site to nginx
      template:
        src: gateway/nginx-site.conf.j2
        dest: "/etc/nginx/sites-available/{{ prime_hostname }}.conf"
      notify:
        - Reload nginx

    - name: Enable nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ prime_hostname }}.conf
        dest: /etc/nginx/sites-enabled/{{ prime_hostname }}.conf
        state: link
      notify:
        - Reload nginx

    - name: Get & install ssl certificate
      command: "certbot --nginx -d  {{ prime_hostname }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --redirect" 
 
  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

- name: Create etc/hosts
  hosts: all
  tasks:
    - name: Replace after the expression till the end of the file (requires Ansible >= 2.4)
      command:
        cmd: "sed -i '/^# ANSIBLE managed hosts entries # DONT ADD OR CHANGE SOMETHING BEYOND THIS LINE$/,$ d' /etc/hosts"
        warn: false
    - name: Add line to mark ansible managed host entries
      lineinfile:
        dest: /etc/hosts
        regexp: '^# ANSIBLE managed hosts entries #.*$'
        line: "# ANSIBLE managed hosts entries # DONT ADD OR CHANGE SOMETHING BEYOND THIS LINE"
        state: present
    - name: Add IP address of all hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].local_ip }} {{ item }} {{ item | regex_replace('([^.]+)\\..*$', '\\1') }}"
        state: present
      when: hostvars[item].local_ip is defined
      with_items: "{{ groups['all'] }}"
    - name: Add additional host entries
      lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items: "{{ etc_hosts_additional_entries }}"
      when: etc_hosts_additional_entries is defined

- name: Create Erlang Cookie
  hosts: localhost
  connection: local
  tasks:
    - set_fact:
        # ansible-galaxy collection install community.general
        release_cookie: "{{ query('community.general.random_string', special=false, length=32) | join }}"

- name: Init Steps for Application
  hosts:
    - gateway
    - clustermember
  vars:
    release_cookie: "{{ hostvars['127.0.0.1'].release_cookie }}"
  tasks:
    - name: Create group
      ansible.builtin.group:
        name: deploy
        state: present
    - name: Add deploy user 
      ansible.builtin.user:
        name: deploy
        comment: Running Node
        group: deploy
        home: /opt/prim
        shell: /bin/bash
    - name: Create relases dir
      file:
        path: /opt/prim
        state: directory
        owner: deploy
        group: deploy
    - name: Create prim log folder
      file:
        path: /var/log/prim
        state: directory
        owner: deploy
        group: deploy
    - name: Install systemd unit file
      template:
        src: all/prim.service.j2
        dest: /etc/systemd/system/prim.service
    - name: Enable Service
      systemd:
        name: prim
        daemon_reload: true
        enabled: true

