name: CD
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Get Dependencies
      run: nix-shell --command "mix deps.get"
    - name: Build Release
      run: |
        . $HOME/.asdf/asdf.sh
        asdf install
        MIX_ENV=prod mix local.hex --force && mix local.rebar --force
        MIX_ENV=prod mix assets.deploy
        MIX_ENV=prod mix release main --overwrite
        MIX_ENV=prod mix release worker --overwrite
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./_build/prod/*.tar.gz
        retention-days: 7
  deploy:
    runs-on: [self-hosted]
    needs: [release]
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Download test output files
      uses: actions/download-artifact@v2
      with:
        name: release
        path: ./_build/prod/
    - name: Run Ansible Deployment
      run: |
        nix-shell --command "cd ansible && ansible-playbook -i inventories/prod playbooks/deploy.yml -v --extra-vars version=\$(cat ../VERSION)"
