name: CD
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: [self-hosted]
    env:
      ImageOS: ubuntu20
    steps:
    - uses: actions/checkout@v3
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: 24.3.4.5
        elixir-version: 1.13
        install-rebar: true
        install-hex: true
    - name: Get Dependencies
      run: mix deps.get
    - name: Build Release
      run: |
        MIX_ENV=prod mix local.hex --force && mix local.rebar --force
        MIX_ENV=prod mix assets.deploy
        MIX_ENV=prod mix release main --overwrite
        MIX_ENV=prod mix release worker --overwrite
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: ./_build/prod/*.tar.gz
        retention-days: 7
  deploy:
    runs-on: [self-hosted]
    needs: [release]
    steps:
    - uses: actions/checkout@v3
    - name: Download test output files
      uses: actions/download-artifact@v3
      with:
        name: release
        path: ./_build/prod/
    - name: Run Ansible Deployment
      run: |
        nix-shell --command "cd ansible && ansible-playbook -i inventories/prod playbooks/deploy.yml -v --extra-vars version=\$(cat ../VERSION)"
