name: CI
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Get Dependencies
      run: nix-shell --command "mix deps.get"
    - name: Run Tests
      run: nix-shell --command "mix test"

